version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: todo-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: todo-app
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo-data:
