apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: todo-app
          image: youssefhassan122/todo-app:latest
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE
              value: "mongodb://mongodb:27017/todolistDb"
            - name: PORT
              value: "4000"
          livenessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
