apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: todo-app=docker.io/youssefhassan122/todo-app
    argocd-image-updater.argoproj.io/todo-app.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: kustomize
spec:
  project: default
  source:
    repoURL: https://github.com/youssefsaber0/todo-app.git
    targetRevision: main
    path: k8s-conf/todo-app/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
